# Generated by Django 4.2.5 on 2023-10-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
